dist: xenial

language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - "pip install -r test_requirements.txt"
  - "pip install -r requirements.txt"

script:
  - "python setup.py install"
  - "py.test tests/ --cov mats --cov-report term-missing"
  - "flake8 mats"

after_success:
  - "coveralls"
